# Disable services not needed for this project.
services:
  mariadb:
    profiles:
      - disabled

  mail:
    profiles:
      - disabled

  phpfpm:
    depends_on: !reset []
    environment:
      - PHP_SENDMAIL_PATH=/usr/bin/true
